In [4]:
import torch
import numpy as np

In [5]:
t = torch.tensor([1, 2])
print(t)
print(t.dtype)

tensor([1, 2])
torch.int64


In [6]:
t = torch.FloatTensor([1, 2])
print(t)
print(t.dtype)

tensor([1., 2.])
torch.float32


In [7]:
t = torch.rand(3,4)
print(t)

tensor([[0.9606, 0.9735, 0.6613, 0.0368],
        [0.2009, 0.0362, 0.7645, 0.3504],
        [0.1161, 0.3721, 0.9008, 0.8872]])


In [8]:
if torch.cuda.is_available():
    t = t.to('cuda')
print(t.device)

cuda:0


In [13]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('using {} device'.format(device))
s = torch.rand(2, 3)
print(s.device)
s = s.to(device)
print(s.device)

using cuda device
cpu
cuda:0
